### ISSUE TITLE
Feature : error callback interface

### ISSUE THREAD

**Issue by tiger79** [perthcpe23/android-mjpeg-view#14]
Hi,
I was wondering if as an extra feature an error callback interface could be implemented in the library.
So when the library catches an error, for example not being able to connect to the stream, this could be returned using an interface to the app using the library. This would make it possible, in certain cases, to at least show a message or popup to the user or log the exception to file.
The library is already logging, for example here : 
` try {
                    bis.close();
                    connection.disconnect();
                    Log.i(tag,"disconnected with " + url);
                } catch (Exception e) {
                    if(e.getMessage() != null) {
                        Log.e(tag, e.getMessage());
                    }
                }`

And this is what is shown in Logcat :

2023-04-24 09:17:15.801 18640-19460/nl.organization.myapp E/MjpegView: Failed to connect to streamingserver.organization.nl/188.72.65.150:443
2023-04-24 09:17:15.802 18640-19460/nl.organization.myapp E/MjpegView: Attempt to invoke virtual method 'void java.io.BufferedInputStream.close()' on a null object reference

I also think there  is a bug here, an exception gets thrown whilst trying to close bis object

**Comment by perthcpe23** [comment]
Good idea!

**Comment by punyapat-s** [comment]
https://github.com/perthcpe23/android-mjpeg-view/releases/tag/v1.1.2

**Comment by tiger79** [comment]
Thanks both for approving this rfc and the speedy implementation !
This helps out quite a lot, now that it's possible to log errors from within our app / local log files !
