### ISSUE TITLE
V/MjpegView: Skip drawing, canvas is null or bitmap is not ready yet

### ISSUE THREAD

**Issue by Maxim-Kolmogorov** [perthcpe23/android-mjpeg-view#17]
Hello. When i try use this package, I encountered error: "V/MjpegView: Skip drawing, canvas is null or bitmap is not ready yet" and next i have permanent white screen. I use Jetpack Compose and Kotlin. I set permissions for internet and i can open my http mjpeg stream in Google Chrome. Maybe do you have any idea why it might not work for me?

Screen + method (VideoViewForBroadcast 30 row):
![image](https://github.com/perthcpe23/android-mjpeg-view/assets/48102796/9e0329ef-671b-43ee-8898-0567ead9f91d)

Method for camera:
![image](https://github.com/perthcpe23/android-mjpeg-view/assets/48102796/0ba3da48-daa0-4614-acb1-f7b4c669e378)

Terminal:
![image](https://github.com/perthcpe23/android-mjpeg-view/assets/48102796/b18a6ab2-a43f-4298-9cb0-db2d3c3dbe14)

Result:
![image](https://github.com/perthcpe23/android-mjpeg-view/assets/48102796/694cf03e-73e5-466e-8519-313545764a4a)

**Comment by leonw1112** [comment]
viewer.setRecycleBitmap(true);
        viewer.setStateChangeListener(new MjpegViewStateChangeListener() {

            @Override
            public void onStreamDownloadStart() {
                Log.d("StateChangeListener", "onStreamDownloadStart");
            }

            @Override
            public void onStreamDownloadStop() {
                Log.d("StateChangeListener", "onStreamDownloadStop");
            }

            @Override
            public void onServerConnected() {
                Log.d("StateChangeListener", "onServerConnected");
            }

            @Override
            public void onMeasurementChanged(Rect rect) {
                Log.d("StateChangeListener", "onMeasurementChanged");
            }

            @Override
            public void onNewFrame(Bitmap image) {
            }

            @Override
            public void onError(MjpegViewError error) {
                Log.d("StateChangeListener", String.valueOf(error.errorCode));
            }
        });
        
        
        This should fix it

**Comment by Maxim-Kolmogorov** [comment]
Fixed it a long time ago, but in a different way
