### ISSUE TITLE
Is there a way to zoom the view with pinch gesture?

### ISSUE THREAD

**Issue by roger-zacharczyk** [perthcpe23/android-mjpeg-view#2]

**Comment by yeahman45** [comment]
any news about pinch zoom?

**Comment by yeahman45** [comment]
I got the pinch-and-zoom branch.. it is not perfect but it works :) thx 
I also added basic authentication for my needs.

**Comment by DuduLeitao** [comment]
> I got the pinch-and-zoom branch.. it is not perfect but it works :) thx
> I also added basic authentication for my needs.

How can I change the branch in AndroidStudio?

**Comment by perthcpe23** [comment]
Hi guys, I just release a new version which support pinch-zoom. Please use latest version (v1.0.9) and use `setSupportPinchZoomAndPan(true)` to enable/disable pinch-zoom and pan.
